### ISSUE TITLE
App crashes after upgrading BugSense to SplunkMint

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-capture-android#10]
Upgraded BugSense 3.5 to SplunkMint 4.2 (Tried 4.2.1 but it has the same issue) and got the following crash at line ```Socket clientSocket = serverSocket.accept();```

Changes made are all in commit: https://github.com/evercam/evercam-capture-android/commit/e2ed802b21434a8ed482117fb579ea8fb9b021ad

Crash log:
```
07-16 11:42:33.486  19099-19256/io.evercam.capture E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-36484
    Process: io.evercam.capture, PID: 19099
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileDescriptor.setInt$(int)' on a null object reference
            at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:93)
            at java.net.ServerSocket.implAccept(ServerSocket.java:216)
            at java.net.ServerSocket.accept(ServerSocket.java:140)
            at io.evercam.capture.server.ServerThread.run(ServerThread.java:34)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by liutingdu** [comment]
Discussions:

https://splunkmint.zendesk.com/requests/6022
http://www.ranorex.com/forum/android-studio-build-t8058.html

**Comment by liutingdu** [comment]
http://docs.splunk.com/Documentation/MintAndroidSDK/4.2.x/DevGuide/KnownIssues

From SplunkMint docs: "There are known compatibility issues with network monitoring and server-side sockets. If you use server-side sockets, you should disable network monitoring entirely."
